name: Add a musette
description: This issue is a request to add a new musette to the list
title: "[Musette]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping the inventory!

  - type: input
    id: team
    attributes:
      label: Team name
      placeholder: Team
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year
    validations:
      required: true

  - type: input
    id: category
    attributes:
      label: Category
      placeholder: Professional
    validations:
      required: false

  - type: textarea
    id: picture-front
    attributes:
      label: Picture Front
      description: Attach an image to the issue or paste an image URL here
      placeholder: Drag and drop an image, or paste a URL

  - type: textarea
    id: picture-back
    attributes:
      label: Picture Back
      description: Attach an image to the issue or paste an image URL here
      placeholder: Drag and drop an image, or paste a URL
    validations:
      required: false

  - type: textarea
    id: difference
    attributes:
      label: Difference to previous
      description: Specify what is different on this musette, with the position and the sponsor added/missing
      placeholder: Type here
    validations:
      required: false

  - type: dropdown
    id: do-you-have-the-musette
    attributes:
      label: Do you have the musette?
      options:
        - "Yes"
        - "No"

  - type: input
    id: special-edition
    attributes:
      label: Special Edition ?
      placeholder: Tour, Giro, Vuelta, etc.
