name: Add a musette
description: This issue is a request to add a new musette to the list
title: "[Musette]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping the inventory!

  - type: input
    id: team
    attributes:
      label: Team name
      placeholder: Team
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Year
    validations:
      required: true

  - type: input
    id: category
    attributes:
      label: Category
      placeholder: Professional
    validations:
      required: false

  - type: input
    id: picture-front
    attributes:
      label: Picture Front
      placeholder: Front image URL or filename

  - type: input
    id: picture-back
    attributes:
      label: Picture Back
      placeholder: Back image URL or filename

  - type: textarea
    id: difference
    attributes:
      label: Difference to previous
      description: Specify what is different on this musette, with the position and the sponsor added/missing
      placeholder: Type here
    validations:
      required: false

  - type: input
    id: kevin
    attributes:
      label: Kevin
      description: Use x if applicable, otherwise leave empty
      placeholder: x

  - type: input
    id: special-edition
    attributes:
      label: Special Edition ?
      placeholder: Tour, Giro, Vuelta, etc.

  - type: input
    id: image-path-front
    attributes:
      label: Image path front
      description: Path to the front image in the repository, for example images/filename.png

  - type: input
    id: image-path-back
    attributes:
      label: Image path back
      description: Path to the back image in the repository, for example images/filename.png
    validations:
      required: false
